### ISSUE TITLE
File Not Found Exception

### ISSUE THREAD

**Issue by ZoobiApplications** [Drjacky/ImagePicker#88] opened 2022-12-14 05:29 UTC
File not found exception occurs when picking image from gallery in your latest sample app.

 - OS: Android Studio 
 - Version Dolphin 2021.3.1 Patch 1

 - Device: Samsung Galaxy A03s
 - OS: Android
 - Version 12

Error Snippet:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.drjacky.imagepicker.sample, PID: 24962
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=731911126, result=-1, data=Intent { dat=content://media/picker/0/com.android.providers.media.photopicker/media/1000000299 flg=0x41 clip={image/* video/* {U(content)}} }} to activity {com.github.drjacky.imagepicker.sample/com.github.drjacky.imagepicker.ImagePickerActivity}: java.io.IOException: No such file or directory
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5946)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5985)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
        at java.io.File.createNewFile(File.java:1006)
        at com.github.drjacky.imagepicker.provider.CropProvider.convertBitmapToFile(CropProvider.kt:235)
        at com.github.drjacky.imagepicker.provider.CropProvider.cropImage(CropProvider.kt:166)
        at com.github.drjacky.imagepicker.provider.CropProvider.startIntent(CropProvider.kt:128)
        at com.github.drjacky.imagepicker.ImagePickerActivity.setMultipleCropper(ImagePickerActivity.kt:198)
        at com.github.drjacky.imagepicker.ImagePickerActivity.setMultipleImage(ImagePickerActivity.kt:186)
        at com.github.drjacky.imagepicker.provider.GalleryProvider.handleResult(GalleryProvider.kt:171)
        at com.github.drjacky.imagepicker.provider.GalleryProvider.handleResult(GalleryProvider.kt:154)
        at com.github.drjacky.imagepicker.ImagePickerActivity.galleryLauncher$lambda-0(ImagePickerActivity.kt:54)
        at com.github.drjacky.imagepicker.ImagePickerActivity.$r8$lambda$-cKXUbSEPsgVWIyQVksiDayv-z4(Unknown Source:0)
        at com.github.drjacky.imagepicker.ImagePickerActivity$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
        at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
        at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
        at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:647)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:140)
        at android.app.Activity.dispatchActivityResult(Activity.java:8659)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5939)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5985) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8751) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by ZoobiApps** [comment] 2022-12-14 06:46
I tested this sample app yesterday and it was working fine but today it is showing me same exception. Don't know what happened!

**Comment by ZoobiApps** [comment] 2022-12-14 07:30
it is not picking the images from recents that are shown for the very first time,... but when we click on browse and select from files it's working fine.

Here are the screenshots.

![Screenshot_20221214-122610 1](https://user-images.githubusercontent.com/105642803/207532748-ea7915e9-6d9d-4b11-a4e9-3762370b7254.png)
![Screenshot_20221214-122620 1](https://user-images.githubusercontent.com/105642803/207532801-3ae7c1e7-a8c8-4762-b806-17fc50ddb56a.png)
![Screenshot_20221214-122645 1](https://user-images.githubusercontent.com/105642803/207532842-3b3550dd-dc71-44db-b0ff-79948fa3d046.png)

**Comment by ashifali3147** [comment] 2022-12-14 12:33
I am facing the same issue today.

**Comment by ZoobiApps** [comment] 2022-12-14 12:34
@Drjacky ?

**Comment by ibrahim-sdsol** [comment] 2022-12-15 14:54
Facing same issue

**Comment by mandocarrilloh** [comment] 2022-12-15 18:02
@Drjacky same issue 2 days ago

**Comment by ashifali3147** [comment] 2022-12-16 05:09
Check [ImagePicker](https://github.com/Dhaval2404/ImagePickerl) this library.

**Comment by ZoobiApplications** [comment] 2022-12-19 07:57
@Catlandor thankyou so much for the Bugfix.

**Comment by Drjacky** [comment] 2022-12-19 11:16
Thanks to @Catlandor, fixed on [2.3.21](https://github.com/Drjacky/ImagePicker/releases/tag/2.3.21)

**Closed by Drjacky** 2022-12-19 11:16 UTC
Labels: bug

**Comment by Catlandor** [comment] 2022-12-19 11:33
@Drjacky: Thanks for including my fix, but the changes within the "GalleryProvider" are needed as well.
When picking an image with the Android photo picker it treats this as a "multiple image" selection, even though it is not.

If you do not include this changes, the returned result for a single image selection via the Android photo picker will be always null (uri of the image).

**Comment by Drjacky** [comment] 2022-12-19 17:17
Fixed on [2.3.22](https://github.com/Drjacky/ImagePicker/releases/tag/2.3.22).
Thanks!

**Comment by omariassidi** [comment] 2022-12-23 14:11
Heyy, I know this is closed, but can I know what are the retro steps? It happened with some of our users, but we did not know when and how. 
Thanks.

**Comment by Catlandor** [comment] 2022-12-23 15:02
It's related to the Android photo picker, which was released with SDK version 33 of Android. Also see:
https://developer.android.com/training/data-storage/shared/photopicker

When opening the gallery, the photo picker was opened (instead of the default gallery folder view) and selecting an image with this (new) photo picker had two issues with the previous implementation (release 2.3.20):

- This file didn't end with ".jpg", ".png", it had a generated file name like "1000000033". Since the previous implementation looked for the last period to identify the mime type of the file, this failed here and later led to above mentioned exception "File Not Found" (actually it couldn't create a file, since it didn't have a mime type).
- When selecting an image via Android photo picker, it was treated as a multiple image selection, even if it was not. This led to a null reference exception when trying to get the uri of the image within the returned result.

Second issue also could been reproduced by opening the gallery, then navigating the Google Photos (via hamburger menu on the top left) and selecting an image from here.

Both issues are fixed with release 2.3.22

**Comment by omariassidi** [comment] 2022-12-23 15:18
Thank you for the clarification
